/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_daniel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author DFR.
 */
public class Tela_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro
     */
    public Tela_Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nome = new javax.swing.JLabel();
        jLabel_Sourname = new javax.swing.JLabel();
        jTextField_DigiteNome = new javax.swing.JTextField();
        jTextField_Sobrenome = new javax.swing.JTextField();
        jButton_Cadastro = new javax.swing.JButton();
        jButton_att = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jTextField_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_cpf = new javax.swing.JTextField();
        jLabel_cpf = new javax.swing.JLabel();
        jButton_consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Nome.setText("Primeiro nome");

        jLabel_Sourname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Sourname.setText("Sobrenome");

        jTextField_DigiteNome.setText("Digite seu nome");
        jTextField_DigiteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DigiteNomeActionPerformed(evt);
            }
        });

        jTextField_Sobrenome.setText("Enter sourname");
        jTextField_Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SobrenomeActionPerformed(evt);
            }
        });

        jButton_Cadastro.setText("Cadastrar");
        jButton_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastroActionPerformed(evt);
            }
        });

        jButton_att.setText("Atualizar");
        jButton_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_attActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Deletar");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jTextField_ID.setText("ID");
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID (somente para consulta, update e delete) ");

        jTextField_cpf.setText("Digite CPF");

        jLabel_cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_cpf.setText("Digite o seu cpf válido :)");

        jButton_consultar.setText("Consultar");
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(604, 604, 604)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_cpf)
                            .addComponent(jButton_att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(jLabel_cpf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Nome)
                                    .addComponent(jTextField_DigiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Sourname)
                                    .addComponent(jTextField_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome)
                    .addComponent(jLabel_Sourname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_DigiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_cpf)
                .addGap(18, 18, 18)
                .addComponent(jTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton_Cadastro)
                .addGap(34, 34, 34)
                .addComponent(jButton_att)
                .addGap(34, 34, 34)
                .addComponent(jButton_Delete)
                .addGap(34, 34, 34)
                .addComponent(jButton_consultar)
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_DigiteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DigiteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DigiteNomeActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SobrenomeActionPerformed

    private void jButton_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastroActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            Connection conexao = DriverManager.getConnection (url, usuario, senha);
            String sql = "INSERT INTO Banco_Cadastro(nome,sobrenome,cpf, id) VALUES (?, ?, ?, ?)";
            
            PreparedStatement statement = conexao.prepareStatement(sql);
            statement.setString(1, jTextField_DigiteNome.getText());
            statement.setString(2, jTextField_Sobrenome.getText());
            statement.setString(3, jTextField_cpf.getText());
            statement.executeUpdate();
            
            System.out.println("Cadastro realizado");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_CadastroActionPerformed

    private void jButton_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_attActionPerformed
            
        try {
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            Connection conexao = DriverManager.getConnection (url, usuario, senha);
            String sql = "UPDATE Banco_Cadastro SET nome = ?,sobrenome = ?, cpf = ?  where id_aluno = ?";
            
            PreparedStatement statement = conexao.prepareStatement(sql);
            statement.setString(1, jTextField_DigiteNome.getText());
            statement.setString(2, jTextField_Sobrenome.getText());
            statement.setString(3, jTextField_cpf.getText());
            statement.setString(4, jTextField_ID.getText());
            statement.executeUpdate();
            
            System.out.println("Cadastro atualizado com sucesso!");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_attActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/Projeto_17";
            String usuario = "root";
            String senha = "";
            
            Connection conexao = DriverManager.getConnection (url, usuario, senha);
            String sql = "DELETE from Banco_cadasto where id = ?";
            
            PreparedStatement statement = conexao.prepareStatement(sql);
            statement.setString(1, jTextField_ID.getText());

            statement.executeUpdate();
            
            System.out.println("Deu certo");
            
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastro;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_att;
    private javax.swing.JButton jButton_consultar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_Sourname;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JTextField jTextField_DigiteNome;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Sobrenome;
    private javax.swing.JTextField jTextField_cpf;
    // End of variables declaration//GEN-END:variables
}
